<?php
/**
 * Copyright © PART <info@part-online.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>
<script>
require(["jquery", "prototype"], function(jQuery) {
    jQuery(function(){
        var isFilterableSelectedIndex = $('is_filterable').selectedIndex;
        setTimeout(function() {
            var frontendInput = $('frontend_input');

            function bindAttributeInputType() {
                var isFilterable = $('is_filterable'),
                    isFilterableInSearch = $('is_filterable_in_search'),
                    position = $('position');
                if (frontendInput && frontendInput.value === 'number') {
                    if (isFilterable) {
                        isFilterable.selectedIndex = isFilterableSelectedIndex;
                        isFilterable.disabled = false;
                        if (isFilterable.selectedIndex == 0) {
                            position.disabled = true;
                        } else {
                            if (!position.getAttribute('readonly')) {
                                position.disabled = false;
                            }
                        }
                    }
                    if (isFilterableInSearch) {
                        isFilterableInSearch.disabled = false;
                    }
                }
            }
            if(frontendInput){
                Event.observe(frontendInput, 'change', bindAttributeInputType);
            }
            bindAttributeInputType();
        }, 3000);
    });
});
</script>
